### PR TITLE
Added functionality for adding colon to icon/image name

### PR DESCRIPTION
**Pull request by runesr**
I made a small addon to the existing code. So it adds a colon before and after the image/icon name, if the user forgets to add it. So that you will get the correct icon either you remember to add the colons or not.

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
Thanks @runesr

**Comment by BenRomberg** [comment]
FYI @ashwanthkumar, this broke my Slack integration since it was putting colons around my absolute URLs (not using emojis as icons) and it was really hard to debug.

The following code in `SlackService` is now probably useless, since the icon will always start with `:` and it will always send it as an `icon_emoji`:

```
        if (startsWith(imageOrIcon, "http")) {
            payload.put("icon_url", imageOrIcon);
        } else if (isNotEmpty(imageOrIcon)) {
            payload.put("icon_emoji", imageOrIcon);
        }
```

Or am I missing something?

**Comment by ashwanthkumar** [comment]
@BenRomberg I'm so sorry about that, I've now fixed it as part of https://github.com/ashwanthkumar/slack-java-webhook/commit/9acab0b2b11577093a04c52231c3eaf8c43019d9 with a test. Thanks for the report, this fix is available in the [next release](https://github.com/ashwanthkumar/slack-java-webhook/releases/tag/0.0.9). It's available on Sonatype Releases and will be available on Maven Central in a while.

**Comment by BenRomberg** [comment]
@ashwanthkumar thanks a lot for the swift fix! I've also enhanced our code with some more integration tests, making sure it sends an `icon_url` with the proper URL.

Thanks a lot for your continued support of the Slack library!

**Pull request merged**
